name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'data/**'
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # [关于在 GitHub Action 中无法获取 Git 历史的问题 | HeyFE](https://blog.heyfe.org/blog/git-history-in-github-action.html) 默认浅克隆，但是这样的话docusaurus docs mode下无法获得history，showLastUpdateTime就不生效了。
      - uses: actions/setup-node@main
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build website
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      #      - name: Deploy to GitHub Pages
      #        uses: peaceiris/actions-gh-pages@v3
      #        with:
      #          github_token: ${{ secrets.GITHUB_TOKEN }}
      #          # Build output to publish to the `gh-pages` branch:
      #          publish_dir: ./build
      #          # The following lines assign commit authorship to the official
      #          # GH-Actions bot for deploys to `gh-pages` branch:
      #          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
      #          # The GH actions bot is used by default if you didn't specify the two fields.
      #          # You can swap them out with your own user credentials.
      #          user_name: github-actions[bot]
      #          user_email: 41898282+github-actions[bot]@users.noreply.github.com

      #      - name: Publish to Cloudflare Pages
      #        uses: cloudflare/pages-action@v1
      #        with:
      #          apiToken: ${{ secrets.CF_API_TOKEN }}
      #          accountId: ${{ secrets.CF_ACCOUNT_ID }}
      #          projectName: docs
      #          directory: build
      #          wranglerVersion: '3' # Enable Wrangler v3
      #          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      #          branch: gh-pages

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy "build" --project-name="blog" --branch="gh-pages"
